#!/usr/bin/env python3
"""Build carrom.tap: a BASIC loader (title page + keys) followed by the machine code."""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
T = {'CLEAR': 0xFD, 'BORDER': 0xE7, 'PAPER': 0xDA, 'INK': 0xD9, 'BRIGHT': 0xDC, 'CLS': 0xFB,
     'PRINT': 0xF5, 'AT': 0xAC, 'LOAD': 0xEF, 'CODE': 0xAF, 'RANDOMIZE': 0xF9, 'USR': 0xC0,
     'FLASH': 0xDB}

def num(n):
    """A number literal: its digits followed by the hidden 5-byte small-integer form."""
    return str(n).encode() + bytes([0x0E, 0, 0, n & 255, n >> 8, 0])

def line(no, *parts):
    body = b''
    for p in parts:
        if isinstance(p, int):
            body += bytes([p])
        elif isinstance(p, bytes):
            body += p
        else:
            body += p.encode('ascii')
    body += b'\r'
    return bytes([no >> 8, no & 255, len(body) & 255, len(body) >> 8]) + body

def q(s):
    return '"' + s + '"'

def at(r, c):
    return bytes([T['AT']]) + num(r) + b',' + num(c) + b';'

title_lines = [
    line(10, T['CLEAR'], num(32767)),
    line(20, T['BORDER'], num(0), ':', T['PAPER'], num(0), ':', T['INK'], num(7), ':',
         T['BRIGHT'], num(0), ':', T['CLS']),
    line(30, T['PRINT'], at(2, 5), T['INK'], num(6), ';', q("C A R R O M   A R E N A")),
    line(40, T['PRINT'], at(4, 3), T['INK'], num(5), ';', q("ZX Spectrum 48K machine code")),
    line(50, T['PRINT'], at(5, 8), q("SANYALnet Labs 2026")),
    line(60, T['PRINT'], at(8, 1), q("Four robots play doubles carrom"),
         b';' + bytes([T['AT']]) + num(9), b',', num(1), b';', q("under ICF rules. Just watch!")),
    line(70, T['PRINT'], at(11, 1), T['INK'], num(4), ';', q("RED (N/S) v BLUE (E/W)"),
         b';' + bytes([T['AT']]) + num(12), b',', num(1), b';', q("N aggressive  E balanced"),
         b';' + bytes([T['AT']]) + num(13), b',', num(1), b';', q("S defensive   W trickster")),
    line(80, T['PRINT'], at(15, 1), q("SPACE pause    F  fast/normal"),
         b';' + bytes([T['AT']]) + num(16), b',', num(1), b';', q("M     sound    R  new match"),
         b';' + bytes([T['AT']]) + num(17), b',', num(1), b';', q("Q     quit to BASIC")),
    line(85, T["PRINT"], at(6, 1), T['INK'], num(5), ';', q("Music: nanobeep / utz + Carrom groove")),
    line(90, T['PRINT'], at(19, 9), T['FLASH'], num(1), ';', q(" LOADING ")),
]
prog = b''.join(title_lines + [
    line(100, T['LOAD'], q(""), T['CODE']),
    line(110, T['RANDOMIZE'], T['USR'], num(32768)),
])

def block(flag, data):
    payload = bytes([flag]) + data
    chk = 0
    for b in payload:
        chk ^= b
    payload += bytes([chk])
    return len(payload).to_bytes(2, 'little') + payload

def header(typ, name, length, p1, p2):
    nm = name.ljust(10)[:10].encode('ascii')
    return block(0x00, bytes([typ]) + nm + length.to_bytes(2, 'little') +
                 p1.to_bytes(2, 'little') + p2.to_bytes(2, 'little'))

bin_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'carrom.bin')
code = open(bin_path, 'rb').read()
tap = header(0, 'CarromZX', len(prog), 10, len(prog)) + block(0xFF, prog)
tap += header(3, 'carrom', len(code), 32768, 32768) + block(0xFF, code)
# the turbo (ZQLoader) edition: the same title page, then the REM-resident loader
# (zq/zqloader_carrom.z80asm) pulls the code in, returns, and line 110 starts the game
zq = ["; generated by mktap.py: the BASIC in front of the ZQLoader REM line"]
for ln in title_lines + [line(110, T['RANDOMIZE'], T['USR'], num(32768))]:
    if ln[:2] == bytes([0, 110]):
        zq += ["        db 0,100,10,0,0xF9,0xC0,'0',0x0E,0,0   ; 100 RANDOMIZE USR ASM_START",
               "        dw ASM_START", "        db 0,0x0D"]
    for i in range(0, len(ln), 32):
        zq.append("        db " + ",".join(str(x) for x in ln[i:i + 32]))
loader_dir = sys.argv[3] if len(sys.argv) > 3 else os.path.join(HERE, 'zq')
os.makedirs(loader_dir, exist_ok=True)
open(os.path.join(loader_dir, 'zq_basic.inc'), 'w').write("\n".join(zq) + "\n")
# what ZQLoader's host tool turbo-loads: CLEAR + LOAD ""CODE, no USR, so the loader returns to
# our BASIC (line 110 starts the game, and Q can still quit back to BASIC)
zprog = line(10, T['CLEAR'], num(32767)) + line(20, T['LOAD'], q(""), T['CODE'])
codetap = (header(0, 'CarromZX', len(zprog), 10, len(zprog)) + block(0xFF, zprog) +
           header(3, 'carrom', len(code), 32768, 32768) + block(0xFF, code))
open(os.path.join(loader_dir, 'carrom_code.tap'), 'wb').write(codetap)

out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, 'carrom.tap')
open(out, 'wb').write(tap)
print(f"{out}: BASIC {len(prog)} bytes, code {len(code)} bytes, tape {len(tap)} bytes")
