; Carrom Arena music generated by music.py
; blocking songs use a callable adaptation of utz nanobeep
; source authority: tuklusan/ZX-Spectrum-1-Bit-Routines/nanobeep
SONG_TITLE:
        dw 320
        dw SONG_TITLE_loopseq
        dw SONG_TITLE_p0-1
        dw SONG_TITLE_p1-1
        dw SONG_TITLE_p2-1
        dw SONG_TITLE_p3-1
SONG_TITLE_loopseq:
        dw SONG_TITLE_p4-1
        dw SONG_TITLE_p5-1
        dw SONG_TITLE_p6-1
        dw SONG_TITLE_p7-1
        dw SONG_TITLE_p8-1
        dw SONG_TITLE_p9-1
        dw SONG_TITLE_p10-1
        dw SONG_TITLE_p11-1
        dw SONG_TITLE_p12-1
        dw SONG_TITLE_p13-1
        dw SONG_TITLE_p14-1
        dw SONG_TITLE_p15-1
        dw SONG_TITLE_p16-1
        dw SONG_TITLE_p17-1
        dw SONG_TITLE_p18-1
        dw SONG_TITLE_p19-1
        dw 0
SONG_TITLE_p0:
        db 0,10
        db 0,10
        db 0,21
        db 0,21
        db 0,10
        db 0,10
        db 0,21
        db 0,21
        db 0,10
        db 0,10
        db 0,21
        db 0,21
        db 0,10
        db 0,10
        db 0,21
        db 0,21
        db 0xFF
SONG_TITLE_p1:
        db 0,8
        db 0,8
        db 0,17
        db 0,17
        db 0,8
        db 0,8
        db 0,17
        db 0,17
        db 0,8
        db 0,8
        db 0,17
        db 0,17
        db 0,8
        db 0,8
        db 0,17
        db 0,17
        db 0xFF
SONG_TITLE_p2:
        db 0,12
        db 0,12
        db 0,25
        db 0,25
        db 0,12
        db 0,12
        db 0,25
        db 0,25
        db 0,12
        db 0,12
        db 0,25
        db 0,25
        db 0,12
        db 0,12
        db 0,25
        db 0,25
        db 0xFF
SONG_TITLE_p3:
        db 0,9
        db 0,9
        db 0,19
        db 0,19
        db 0,9
        db 0,9
        db 0,19
        db 0,19
        db 0,9
        db 0,9
        db 0,19
        db 0,19
        db 0,9
        db 0,9
        db 0,19
        db 0,19
        db 0xFF
SONG_TITLE_p4:
        db 31,10
        db 31,10
        db 31,21
        db 31,21
        db 42,10
        db 42,10
        db 42,21
        db 42,21
        db 50,10
        db 50,10
        db 50,21
        db 50,21
        db 47,10
        db 47,10
        db 42,21
        db 42,21
        db 0xFF
SONG_TITLE_p5:
        db 50,8
        db 50,8
        db 50,17
        db 50,17
        db 42,8
        db 42,8
        db 42,17
        db 42,17
        db 33,8
        db 33,8
        db 33,17
        db 33,17
        db 42,8
        db 42,8
        db 42,17
        db 42,17
        db 0xFF
SONG_TITLE_p6:
        db 37,12
        db 37,12
        db 37,25
        db 37,25
        db 50,12
        db 50,12
        db 50,25
        db 50,25
        db 63,12
        db 63,12
        db 63,25
        db 63,25
        db 56,12
        db 56,12
        db 50,25
        db 50,25
        db 0xFF
SONG_TITLE_p7:
        db 47,9
        db 47,9
        db 47,19
        db 47,19
        db 37,9
        db 37,9
        db 37,19
        db 37,19
        db 28,9
        db 28,9
        db 28,19
        db 28,19
        db 37,9
        db 37,9
        db 37,19
        db 37,19
        db 0xFF
SONG_TITLE_p8:
        db 63,10
        db 63,10
        db 63,21
        db 63,21
        db 56,10
        db 56,10
        db 50,21
        db 50,21
        db 47,10
        db 47,10
        db 47,21
        db 47,21
        db 42,10
        db 42,10
        db 42,21
        db 42,21
        db 0xFF
SONG_TITLE_p9:
        db 50,8
        db 50,8
        db 50,17
        db 50,17
        db 42,8
        db 42,8
        db 33,17
        db 33,17
        db 42,8
        db 42,8
        db 50,17
        db 50,17
        db 56,8
        db 56,8
        db 56,17
        db 56,17
        db 0xFF
SONG_TITLE_p10:
        db 63,12
        db 63,12
        db 63,25
        db 63,25
        db 37,12
        db 37,12
        db 37,25
        db 37,25
        db 50,12
        db 50,12
        db 63,25
        db 63,25
        db 37,12
        db 37,12
        db 37,25
        db 37,25
        db 0xFF
SONG_TITLE_p11:
        db 56,9
        db 56,9
        db 56,19
        db 56,19
        db 47,9
        db 47,9
        db 37,19
        db 37,19
        db 47,9
        db 47,9
        db 56,19
        db 56,19
        db 0,9
        db 0,9
        db 0,19
        db 0,19
        db 0xFF
SONG_TITLE_p12:
        db 33,14
        db 33,14
        db 42,28
        db 42,28
        db 56,14
        db 56,14
        db 56,28
        db 56,28
        db 50,14
        db 50,14
        db 42,28
        db 42,28
        db 33,14
        db 33,14
        db 33,28
        db 33,28
        db 0xFF
SONG_TITLE_p13:
        db 31,10
        db 31,10
        db 42,21
        db 42,21
        db 50,10
        db 50,10
        db 50,21
        db 50,21
        db 47,10
        db 47,10
        db 42,21
        db 42,21
        db 31,10
        db 31,10
        db 31,21
        db 31,21
        db 0xFF
SONG_TITLE_p14:
        db 28,14
        db 28,14
        db 33,28
        db 33,28
        db 42,14
        db 42,14
        db 56,28
        db 56,28
        db 63,14
        db 63,14
        db 56,28
        db 56,28
        db 50,14
        db 50,14
        db 42,28
        db 42,28
        db 0xFF
SONG_TITLE_p15:
        db 47,8
        db 47,8
        db 47,16
        db 47,16
        db 39,8
        db 39,8
        db 39,16
        db 39,16
        db 31,8
        db 31,8
        db 39,16
        db 39,16
        db 47,8
        db 47,8
        db 47,16
        db 47,16
        db 0xFF
SONG_TITLE_p16:
        db 33,14
        db 33,14
        db 42,28
        db 42,28
        db 56,14
        db 56,14
        db 56,28
        db 56,28
        db 50,14
        db 50,14
        db 42,28
        db 42,28
        db 33,14
        db 33,14
        db 33,28
        db 33,28
        db 0xFF
SONG_TITLE_p17:
        db 31,10
        db 31,10
        db 42,21
        db 42,21
        db 50,10
        db 50,10
        db 50,21
        db 50,21
        db 63,10
        db 63,10
        db 56,21
        db 56,21
        db 50,10
        db 50,10
        db 50,21
        db 50,21
        db 0xFF
SONG_TITLE_p18:
        db 47,8
        db 47,8
        db 47,16
        db 47,16
        db 63,8
        db 63,8
        db 63,16
        db 63,16
        db 56,8
        db 56,8
        db 50,16
        db 50,16
        db 47,8
        db 47,8
        db 39,16
        db 39,16
        db 0xFF
SONG_TITLE_p19:
        db 42,10
        db 42,10
        db 42,21
        db 42,21
        db 42,10
        db 42,10
        db 42,21
        db 42,21
        db 31,10
        db 31,10
        db 31,21
        db 31,21
        db 42,10
        db 42,10
        db 0,21
        db 0,21
        db 0xFF
SONG_BOARD:
        dw 250
        dw 0
        dw SONG_BOARD_p0-1
        dw SONG_BOARD_p1-1
        dw 0
SONG_BOARD_p0:
        db 25,12
        db 31,12
        db 37,12
        db 50,12
        db 50,19
        db 50,19
        db 63,19
        db 63,19
        db 63,12
        db 63,12
        db 63,25
        db 63,25
        db 56,9
        db 56,9
        db 63,19
        db 63,19
        db 0xFF
SONG_BOARD_p1:
        db 75,12
        db 75,12
        db 75,25
        db 75,25
        db 75,12
        db 75,12
        db 75,25
        db 75,25
        db 63,12
        db 63,12
        db 63,12
        db 63,12
        db 0,0
        db 0,0
        db 0,0
        db 0,0
        db 0xFF
SONG_GAME:
        dw 270
        dw 0
        dw SONG_GAME_p0-1
        dw SONG_GAME_p1-1
        dw SONG_GAME_p2-1
        dw SONG_GAME_p3-1
        dw 0
SONG_GAME_p0:
        db 42,8
        db 42,8
        db 50,17
        db 50,17
        db 63,8
        db 63,8
        db 63,17
        db 63,17
        db 56,8
        db 56,8
        db 50,17
        db 50,17
        db 56,8
        db 56,8
        db 63,17
        db 63,17
        db 0xFF
SONG_GAME_p1:
        db 37,9
        db 37,9
        db 47,19
        db 47,19
        db 56,9
        db 56,9
        db 56,19
        db 56,19
        db 50,9
        db 50,9
        db 47,19
        db 47,19
        db 50,9
        db 50,9
        db 56,19
        db 56,19
        db 0xFF
SONG_GAME_p2:
        db 63,12
        db 63,12
        db 63,25
        db 63,25
        db 50,12
        db 50,12
        db 50,25
        db 50,25
        db 37,12
        db 37,12
        db 50,25
        db 50,25
        db 63,12
        db 63,12
        db 63,25
        db 63,25
        db 0xFF
SONG_GAME_p3:
        db 50,12
        db 50,12
        db 50,12
        db 50,12
        db 50,12
        db 50,12
        db 50,12
        db 50,12
        db 75,12
        db 75,12
        db 75,12
        db 75,12
        db 75,0
        db 75,0
        db 0,0
        db 0,0
        db 0xFF
SONG_MATCH:
        dw 285
        dw 0
        dw SONG_MATCH_p0-1
        dw SONG_MATCH_p1-1
        dw SONG_MATCH_p2-1
        dw SONG_MATCH_p3-1
        dw SONG_MATCH_p4-1
        dw SONG_MATCH_p5-1
        dw SONG_MATCH_p6-1
        dw SONG_MATCH_p7-1
        dw 0
SONG_MATCH_p0:
        db 31,10
        db 31,10
        db 31,21
        db 31,21
        db 42,10
        db 42,10
        db 42,21
        db 42,21
        db 50,10
        db 50,10
        db 50,21
        db 50,21
        db 47,10
        db 47,10
        db 42,21
        db 42,21
        db 0xFF
SONG_MATCH_p1:
        db 50,8
        db 50,8
        db 50,17
        db 50,17
        db 42,8
        db 42,8
        db 42,17
        db 42,17
        db 33,8
        db 33,8
        db 33,17
        db 33,17
        db 42,8
        db 42,8
        db 42,17
        db 42,17
        db 0xFF
SONG_MATCH_p2:
        db 37,12
        db 37,12
        db 37,25
        db 37,25
        db 50,12
        db 50,12
        db 50,25
        db 50,25
        db 63,12
        db 63,12
        db 63,25
        db 63,25
        db 56,12
        db 56,12
        db 50,25
        db 50,25
        db 0xFF
SONG_MATCH_p3:
        db 47,9
        db 47,9
        db 47,19
        db 47,19
        db 37,9
        db 37,9
        db 37,19
        db 37,19
        db 28,9
        db 28,9
        db 28,19
        db 28,19
        db 37,9
        db 37,9
        db 37,19
        db 37,19
        db 0xFF
SONG_MATCH_p4:
        db 63,8
        db 63,8
        db 63,17
        db 63,17
        db 56,8
        db 56,8
        db 50,17
        db 50,17
        db 47,8
        db 47,8
        db 47,17
        db 47,17
        db 42,8
        db 42,8
        db 42,17
        db 42,17
        db 0xFF
SONG_MATCH_p5:
        db 56,9
        db 56,9
        db 56,19
        db 56,19
        db 47,9
        db 47,9
        db 37,19
        db 37,19
        db 47,9
        db 47,9
        db 56,19
        db 56,19
        db 56,9
        db 56,9
        db 56,19
        db 56,19
        db 0xFF
SONG_MATCH_p6:
        db 50,12
        db 50,12
        db 63,25
        db 63,25
        db 75,12
        db 75,12
        db 75,25
        db 75,25
        db 75,12
        db 75,12
        db 75,25
        db 75,25
        db 63,12
        db 63,12
        db 63,25
        db 63,25
        db 0xFF
SONG_MATCH_p7:
        db 50,12
        db 50,12
        db 50,12
        db 50,12
        db 50,12
        db 50,12
        db 50,12
        db 50,12
        db 50,12
        db 50,12
        db 50,12
        db 50,12
        db 0,0
        db 0,0
        db 0,0
        db 0,0
        db 0xFF

; in-game Bollywood-EDM-inspired groove for groove.asm (generated by music.py)
GM_STEPF EQU 6
GM_SONG:
        dw GM_PAT0
        dw GM_PAT1
        dw GM_PAT2
        dw GM_PAT3
        dw GM_PAT4
        dw GM_PAT5
        dw GM_PAT6
        dw GM_PAT7
        dw GM_PAT8
        dw GM_PAT9
        dw GM_PAT10
        dw GM_PAT11
        dw GM_PAT12
        dw GM_PAT13
        dw GM_PAT14
        dw GM_PAT15
        dw GM_PAT16
        dw GM_PAT17
        dw GM_PAT18
        dw GM_PAT19
        dw GM_PAT20
        dw GM_PAT21
        dw GM_PAT22
        dw GM_PAT23
        dw GM_PAT24
        dw GM_PAT25
        dw GM_PAT26
        dw GM_PAT27
        dw GM_PAT28
        dw GM_PAT29
        dw GM_PAT30
        dw GM_PAT31
        dw 0
GM_PAT0:  db 65,192,2,195,128,196,69,192,65,192,3,194,128,198,67,192
GM_PAT1:  db 71,192,72,196,128,193,9,192,71,192,68,200,128,195,4,192
GM_PAT2:  db 68,192,10,203,128,195,76,192,68,192,10,195,128,204,74,192
GM_PAT3:  db 73,192,74,204,128,197,65,192,73,128,76,138,64,133,76,128
GM_PAT4:  db 65,192,67,194,128,203,13,192,66,192,67,196,128,197,14,192
GM_PAT5:  db 71,0,196,200,128,194,74,0,72,192,4,193,128,201,79,192
GM_PAT6:  db 68,192,3,202,128,203,74,192,67,192,12,195,128,202,67,192
GM_PAT7:  db 73,192,69,204,128,202,72,192,76,128,69,129,64,137,76,128
GM_PAT8:  db 76,192,2,208,128,200,67,192,76,192,2,200,128,195,68,192
GM_PAT9:  db 65,192,68,195,128,194,6,192,67,192,68,197,128,193,3,192
GM_PAT10:  db 79,0,197,195,128,198,77,0,81,192,13,198,128,200,67,192
GM_PAT11:  db 65,0,0,194,128,3,0,196,64,5,0,206,128,15,64,192
GM_PAT12:  db 65,196,3,194,128,195,68,192,69,196,3,192,134,195,68,192
GM_PAT13:  db 71,193,68,200,128,196,1,192,73,193,68,192,131,196,1,192
GM_PAT14:  db 68,195,10,203,128,202,67,192,76,195,10,192,141,202,67,192
GM_PAT15:  db 73,197,76,202,128,204,69,192,65,133,76,128,72,140,69,128
GM_PAT16:  db 65,0,3,192,130,0,11,192,77,0,2,192,131,0,68,192
GM_PAT17:  db 82,0,8,192,147,0,16,192,75,0,19,192,136,0,76,192
GM_PAT18:  db 65,192,3,194,128,203,77,194,6,192,67,196,133,192,67,192
GM_PAT19:  db 79,192,69,195,128,198,77,209,64,144,77,134,67,128,67,128
GM_PAT20:  db 65,192,66,195,128,196,5,192,65,196,67,194,128,198,3,196
GM_PAT21:  db 71,192,8,196,128,193,73,192,71,193,4,200,128,195,68,193
GM_PAT22:  db 76,0,208,194,128,200,67,0,76,200,2,208,128,203,66,200
GM_PAT23:  db 79,192,67,197,128,206,69,192,67,134,77,145,64,144,77,134
GM_PAT24:  db 65,196,3,194,139,205,66,195,68,192,5,196,131,198,67,196
GM_PAT25:  db 71,193,68,200,130,202,8,196,65,192,73,193,132,195,4,193
GM_PAT26:  db 68,3,202,203,145,208,75,10,67,192,12,195,138,205,74,195
GM_PAT27:  db 73,197,76,202,141,194,74,204,69,128,65,133,76,136,76,133
GM_PAT28:  db 76,192,8,194,128,208,75,192,66,192,8,195,128,204,66,192
GM_PAT29:  db 79,192,78,197,128,195,6,192,77,192,70,200,128,195,5,192
GM_PAT30:  db 65,192,4,195,128,194,75,192,17,192,75,194,128,195,68,192
GM_PAT31:  db 65,192,67,194,128,203,77,194,70,131,68,133,65,128,67,130
; per note (16 bytes): nanobeep-style phase increment, 4 envelope burst lengths, padding
GM_NOTES:
        db 42,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; A4 440 Hz
        db 84,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; A5 880 Hz
        db 63,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; E5 659 Hz
        db 50,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; C5 523 Hz
        db 47,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; B4 494 Hz
        db 79,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; G#5 831 Hz
        db 33,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; F4 349 Hz
        db 66,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; F5 698 Hz
        db 37,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; G4 392 Hz
        db 75,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; G5 784 Hz
        db 100,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; C6 1047 Hz
        db 56,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; D5 587 Hz
        db 94,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; B5 988 Hz
        db 39,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; G#4 415 Hz
        db 31,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; E4 330 Hz
        db 112,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; D6 1175 Hz
        db 125,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; E6 1319 Hz
        db 44,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; A#4 466 Hz
        db 89,34,24,15,8,0,0,0,0,0,0,0,0,0,0,0   ; A#5 932 Hz
